### ISSUE TITLE
Cutting uplc wasm size from 1.64MB to 935KB

### ISSUE THREAD

**Issue by mpizenberg** [Anastasia-Labs/lucid-evolution#339]
Hi, so I was just having a look at your published npm package `@lucid-evolution/uplc` (https://www.npmjs.com/package/@lucid-evolution/uplc?activeTab=code) and saw that your wasm binaries take 1.64MB.

By applying a few changes to the build setup it is easy to bring them down to 935KB, which can make a significant difference for people loading the web page.

Sorry in advance for not taking the time to do a PR, I’ll just describe the need changes here.

- remove unused dependencies in Cargo.toml. You can get rid of unused dependencies
- update dependencies
- use a more optimized release build profile
- use wee_alloc instead of the default rust allocator
- use a post process step with wasm-opt

In sum, the Cargo.toml interesting sections will look like this:

```toml
[dependencies]
uplc = "1.1.3"
wasm-bindgen = "0.2.93"
js-sys = "0.3.70"
wee_alloc = "0.4.5"
# required for wasm usage of getrandom
getrandom = { version = "0.2", features = ["js"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz']
```

And the beginning of the `lib.rs` file must set the allocator like this:

```rust
use js_sys;
use uplc::tx;
use wasm_bindgen::prelude::*;

// Use `wee_alloc` as the global allocator.
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[wasm_bindgen]
pub fn eval_phase_two_raw(
    tx_bytes: &[u8],
    ...
```

I’m getting the most optimal size when building on CI, gaining a few KB over what I get when building locally, but not sure why, so here is my CI in case useful: https://github.com/mpizenberg/uplc-wasm/blob/4284ff344577bc0c7c7c94cac4d4180189fa3d17/.github/workflows/ci.yml#L21

I hope you find this useful.
